---
# Update package cache and upgrade all packages
- name: Update package cache
  dnf5:
    update_cache: true
  become: true

- name: Upgrade all packages
  dnf5:
    name: "*"
    state: latest
  become: true

# Reboot handling
- name: Check if reboot is required
  command: needs-restarting -r
  register: reboot_required
  changed_when: false
  failed_when: false
  become: true

- name: Reboot system if required
  reboot:
    msg: "Rebooting system due to package updates"
    connect_timeout: "{{ update_settings.connection_timeout }}"
    reboot_timeout: "{{ update_settings.reboot_timeout }}"
    pre_reboot_delay: 0
    post_reboot_delay: "{{ update_settings.post_reboot_delay }}"
    test_command: uptime
  when: reboot_required.rc == 1
  become: true