---
# Configure automatic updates for Fedora
- name: Install dnf-automatic
  package:
    name: dnf-automatic
    state: present

- name: Configure dnf-automatic
  template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start dnf-automatic timer
  systemd:
    name: "dnf-automatic.timer"
    state: started
    enabled: true
    daemon_reload: true