---
# Determine the SSH service name based on the OS family
security_ssh_service: "{{ 'sshd' if ansible_os_family == 'RedHat' else 'ssh' }}"

# SSH port number
security_ssh_port: 22

# SSH configuration options
security_ssh_config:
  permit_root_login: "no"
  password_authentication: "no"
  x11_forwarding: "no"
  max_auth_tries: 3
  protocol: 2