---
# Install and configure firewalld
- name: Install firewall packages
  package:
    name: "{{ security_settings.firewall.packages }}"
    state: present
  become: true

- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: true

- name: Configure firewall ports
  firewalld:
    port: "{{ item.port }}/{{ item.proto }}"
    permanent: true
    state: enabled
  loop: "{{ security_settings.firewall.allowed_ports }}"
  notify: Reload firewalld