---
# Install essential packages
- name: Install essential packages
  package:
    name: "{{ common_packages }}"
    state: present
  become: true
  tags: ['packages']

# Install and configure monitoring
- name: Install monitoring tools
  become: true
  tags: ['monitoring']
  block:
    - name: Install additional monitoring dependencies
      package:
        name:
          - whois
          - geoip
          - geoip
          - logrotate
          - sysstat
        state: present

    - name: Copy fail2ban monitoring script
      copy:
        src: fail2ban-status.sh
        dest: "{{ security_settings.fail2ban.monitoring_script_path }}"
        mode: '0755'
        owner: root
        group: root
      notify: Restart fail2ban

    - name: Create symbolic link for fail2ban-status
      file:
        src: "{{ security_settings.fail2ban.monitoring_script_path }}"
        dest: /usr/bin/f2b
        state: link

    - name: Create log directory
      file:
        path: "{{ security_settings.fail2ban.log_path | dirname }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Set up monitoring cron jobs
      cron:
        name: "{{ item.name }}"
        job: "{{ item.job }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour | default('*') }}"
        user: root
      loop:
        - name: "Check fail2ban status (frequent)"
          job: "/usr/bin/f2b > {{ security_settings.fail2ban.log_path }}"
          minute: "*/5"
        - name: "Generate daily fail2ban report"
          job: "/usr/bin/f2b > {{ security_settings.fail2ban.log_path }}.daily.$(date +\\%Y\\%m\\%d)"
          minute: "0"
          hour: "0"

    - name: Set up log rotation
      copy:
        dest: /etc/logrotate.d/fail2ban-status
        mode: '0644'
        owner: root 
        group: root
        content: |
          {{ security_settings.fail2ban.log_path }} {
            daily
            rotate 7
            compress
            delaycompress
            missingok
            notifempty
            create 0644 root root
          }
          
          {{ security_settings.fail2ban.log_path }}.daily.* {
            weekly
            rotate 52
            compress
            delaycompress
            missingok
            notifempty
            create 0644 root root
          }