---
# Install essential packages based on OS family
- name: Install essential packages
  package:
    name: "{{ common_packages[ansible_os_family] }}"
    state: present
  become: true
  tags: ['packages']

# Install and configure monitoring
- name: Install monitoring tools
  become: true
  tags: ['monitoring']
  block:
    - name: Copy fail2ban monitoring script
      copy:
        src: fail2ban-status.sh
        dest: "{{ security_settings.fail2ban.monitoring_script_path }}"
        mode: '0755'
        owner: root
        group: root
      notify: Restart fail2ban

    - name: Create symbolic link for fail2ban-status
      file:
        src: "{{ security_settings.fail2ban.monitoring_script_path }}"
        dest: /usr/bin/f2b
        state: link

    - name: Create log directory
      file:
        path: "{{ security_settings.fail2ban.log_path | dirname }}"
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Set up monitoring cron job
      cron:
        name: "Check fail2ban status"
        job: "/usr/bin/f2b > {{ security_settings.fail2ban.log_path }}"
        minute: "*/5"  # Run every 5 minutes
        user: root

    - name: Set up log rotation
      copy:
        dest: /etc/logrotate.d/fail2ban-status
        mode: '0644'
        owner: root 
        group: root
        content: |
          {{ security_settings.fail2ban.log_path }} {
            daily
            rotate 7
            compress
            delaycompress
            missingok
            notifempty
            create 0644 root root
          }